---
ohmyzsh_plugins: "git zsh-autosuggestions zsh-syntax-highlighting"
starship_config: |
  [directory]
  truncation_length = 3
  truncate_to_repo = true
  truncation_symbol = 'â€¦/'

  [aws]
  disabled = false

  [terraform]
  format = 'using ðŸ’ ($style) '

  [time]
  disabled = false

  [status]
  disabled = false

  [git_branch]  
  ignore_branches = ['master', 'main']
